# -*- coding: utf-8 -*-
"""P1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyOLNPhfdScrFovRdLpO9OsrZsH71Yv8
"""

checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

position1=input().split()
position2=input().split()

x1,y1 = int(position1[0]),int(position1[1])
x2,y2 = int(position2[0]),int(position2[1])

if checkerboard[x2][y2]==1:
  print('No')
elif (x1==x2 and y1==y2) or (x1!=x2 and y1!=y2 and abs(x2-x1)!=abs(y2-y1)):
  print('No')
else:
  dx = (x2-x1) // max(1,abs(x2-x1))
  dy = (y2-y1) // max(1,abs(y2-y1))

  cx,cy=x1+dx,y1+dy
  reachable=True

  while cx!=x2 or cy!=y2:
    if checkerboard[cx][cy]==1:
      reachable=False
      break
    cx+=dx
    cy+=dy

  if reachable:
    print('Yes')
  else:
    print('No')